# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

# BLE 数据通知类型，与 SensorSDKCXX src/SensorProfileImpl.h 中的 NotifyDataType 保持一致
class DataType(object):
    NONE = 0
    NTF_ACC_DATA = 1
    NTF_GYO_DATA = 2
    NTF_MAG_DATA = 3
    NTF_EULER_DATA = 4
    NTF_QUAT_FLOAT_DATA = 5
    NTF_ROTA_DATA = 6
    NTF_EMG_GEST_DATA = 7
    NTF_EMG_ADC_DATA = 8
    NTF_HID_MOUSE = 9
    NTF_HID_JOYSTICK = 10
    NTF_DEV_STATUS = 11
    NTF_LOG_DATA = 12
    NTF_MAG_ANGLE_DATA = 13
    NTF_MOT_CURRENT_DATA = 14
    NTF_NEUCIR_STATUS = 15
    NTF_EEG = 16
    NTF_ECG = 17
    NTF_IMPEDANCE = 18
    NTF_IMU = 19
    NTF_ADS = 20
    NTF_BRTH = 21
    NTF_IMPEDANCE_EXT = 22
    NTF_SPO2 = 23
    NTF_PPG = 24
    NTF_PARTIAL_DATA = 255
