# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# SensorData 统一数据表
# samples 为一维扁平数组，按通道顺序存放；samples_per_channel 记录每个通道的 sample 数量。
class SensorData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SensorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorData
    def DeviceMac(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SensorData
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def LastPackageCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def LastPackageIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def LostPackageCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def ResolutionBits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def ResolutionSigned(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SensorData
    def ChannelCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def ChannelMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def MinPackageSampleCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def PackageSampleCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def PackageIndexLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SensorData
    def K(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SensorData
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 32
            from sensor.fb.Sample import Sample
            obj = Sample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorData
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorData
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # SensorData
    def SamplesPerChannel(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SensorData
    def SamplesPerChannelAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # SensorData
    def SamplesPerChannelLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorData
    def SamplesPerChannelIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

def SensorDataStart(builder):
    builder.StartObject(16)

def Start(builder):
    SensorDataStart(builder)

def SensorDataAddDeviceMac(builder, deviceMac):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceMac), 0)

def AddDeviceMac(builder, deviceMac):
    SensorDataAddDeviceMac(builder, deviceMac)

def SensorDataAddDataType(builder, dataType):
    builder.PrependUint8Slot(1, dataType, 0)

def AddDataType(builder, dataType):
    SensorDataAddDataType(builder, dataType)

def SensorDataAddLastPackageCounter(builder, lastPackageCounter):
    builder.PrependInt32Slot(2, lastPackageCounter, 0)

def AddLastPackageCounter(builder, lastPackageCounter):
    SensorDataAddLastPackageCounter(builder, lastPackageCounter)

def SensorDataAddLastPackageIndex(builder, lastPackageIndex):
    builder.PrependInt32Slot(3, lastPackageIndex, 0)

def AddLastPackageIndex(builder, lastPackageIndex):
    SensorDataAddLastPackageIndex(builder, lastPackageIndex)

def SensorDataAddLostPackageCount(builder, lostPackageCount):
    builder.PrependInt32Slot(4, lostPackageCount, 0)

def AddLostPackageCount(builder, lostPackageCount):
    SensorDataAddLostPackageCount(builder, lostPackageCount)

def SensorDataAddResolutionBits(builder, resolutionBits):
    builder.PrependInt32Slot(5, resolutionBits, 0)

def AddResolutionBits(builder, resolutionBits):
    SensorDataAddResolutionBits(builder, resolutionBits)

def SensorDataAddResolutionSigned(builder, resolutionSigned):
    builder.PrependInt32Slot(6, resolutionSigned, 0)

def AddResolutionSigned(builder, resolutionSigned):
    SensorDataAddResolutionSigned(builder, resolutionSigned)

def SensorDataAddSampleRate(builder, sampleRate):
    builder.PrependFloat32Slot(7, sampleRate, 0.0)

def AddSampleRate(builder, sampleRate):
    SensorDataAddSampleRate(builder, sampleRate)

def SensorDataAddChannelCount(builder, channelCount):
    builder.PrependInt32Slot(8, channelCount, 0)

def AddChannelCount(builder, channelCount):
    SensorDataAddChannelCount(builder, channelCount)

def SensorDataAddChannelMask(builder, channelMask):
    builder.PrependUint64Slot(9, channelMask, 0)

def AddChannelMask(builder, channelMask):
    SensorDataAddChannelMask(builder, channelMask)

def SensorDataAddMinPackageSampleCount(builder, minPackageSampleCount):
    builder.PrependInt32Slot(10, minPackageSampleCount, 0)

def AddMinPackageSampleCount(builder, minPackageSampleCount):
    SensorDataAddMinPackageSampleCount(builder, minPackageSampleCount)

def SensorDataAddPackageSampleCount(builder, packageSampleCount):
    builder.PrependInt32Slot(11, packageSampleCount, 0)

def AddPackageSampleCount(builder, packageSampleCount):
    SensorDataAddPackageSampleCount(builder, packageSampleCount)

def SensorDataAddPackageIndexLength(builder, packageIndexLength):
    builder.PrependInt32Slot(12, packageIndexLength, 0)

def AddPackageIndexLength(builder, packageIndexLength):
    SensorDataAddPackageIndexLength(builder, packageIndexLength)

def SensorDataAddK(builder, k):
    builder.PrependFloat64Slot(13, k, 0.0)

def AddK(builder, k):
    SensorDataAddK(builder, k)

def SensorDataAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    SensorDataAddSamples(builder, samples)

def SensorDataStartSamplesVector(builder, numElems):
    return builder.StartVector(32, numElems, 4)

def StartSamplesVector(builder, numElems):
    return SensorDataStartSamplesVector(builder, numElems)

def SensorDataAddSamplesPerChannel(builder, samplesPerChannel):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(samplesPerChannel), 0)

def AddSamplesPerChannel(builder, samplesPerChannel):
    SensorDataAddSamplesPerChannel(builder, samplesPerChannel)

def SensorDataStartSamplesPerChannelVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSamplesPerChannelVector(builder, numElems):
    return SensorDataStartSamplesPerChannelVector(builder, numElems)

def SensorDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SensorDataEnd(builder)
